/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_directive = 1,
  anon_sym_LTleader_GT = 2,
  sym_modifier = 3,
  sym_modifier_operator = 4,
  sym_key_operator = 5,
  aux_sym_key_token1 = 6,
  aux_sym_key_token2 = 7,
  aux_sym_key_token3 = 8,
  aux_sym_key_token4 = 9,
  aux_sym_key_token5 = 10,
  aux_sym_key_token6 = 11,
  aux_sym_key_token7 = 12,
  aux_sym_key_token8 = 13,
  sym_separator = 14,
  sym_command = 15,
  sym_comment = 16,
  sym_source_file = 17,
  sym__definition = 18,
  sym_set_leader = 19,
  sym__set_leader = 20,
  sym_keymap = 21,
  sym_hotkey = 22,
  sym__hotkey = 23,
  sym_leader_keymap = 24,
  sym__leader_keymap = 25,
  sym_leader_key = 26,
  sym__leader_key = 27,
  sym_key = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym__hotkey_repeat1 = 30,
  aux_sym__leader_keymap_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_directive] = "directive",
  [anon_sym_LTleader_GT] = "<leader>",
  [sym_modifier] = "modifier",
  [sym_modifier_operator] = "modifier_operator",
  [sym_key_operator] = "key_operator",
  [aux_sym_key_token1] = "key_token1",
  [aux_sym_key_token2] = "key_token2",
  [aux_sym_key_token3] = "key_token3",
  [aux_sym_key_token4] = "key_token4",
  [aux_sym_key_token5] = "key_token5",
  [aux_sym_key_token6] = "key_token6",
  [aux_sym_key_token7] = "key_token7",
  [aux_sym_key_token8] = "key_token8",
  [sym_separator] = "separator",
  [sym_command] = "command",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_set_leader] = "set_leader",
  [sym__set_leader] = "_set_leader",
  [sym_keymap] = "keymap",
  [sym_hotkey] = "hotkey",
  [sym__hotkey] = "_hotkey",
  [sym_leader_keymap] = "leader_keymap",
  [sym__leader_keymap] = "_leader_keymap",
  [sym_leader_key] = "leader_key",
  [sym__leader_key] = "_leader_key",
  [sym_key] = "key",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__hotkey_repeat1] = "_hotkey_repeat1",
  [aux_sym__leader_keymap_repeat1] = "_leader_keymap_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_directive] = sym_directive,
  [anon_sym_LTleader_GT] = anon_sym_LTleader_GT,
  [sym_modifier] = sym_modifier,
  [sym_modifier_operator] = sym_modifier_operator,
  [sym_key_operator] = sym_key_operator,
  [aux_sym_key_token1] = aux_sym_key_token1,
  [aux_sym_key_token2] = aux_sym_key_token2,
  [aux_sym_key_token3] = aux_sym_key_token3,
  [aux_sym_key_token4] = aux_sym_key_token4,
  [aux_sym_key_token5] = aux_sym_key_token5,
  [aux_sym_key_token6] = aux_sym_key_token6,
  [aux_sym_key_token7] = aux_sym_key_token7,
  [aux_sym_key_token8] = aux_sym_key_token8,
  [sym_separator] = sym_separator,
  [sym_command] = sym_command,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_set_leader] = sym_set_leader,
  [sym__set_leader] = sym__set_leader,
  [sym_keymap] = sym_keymap,
  [sym_hotkey] = sym_hotkey,
  [sym__hotkey] = sym__hotkey,
  [sym_leader_keymap] = sym_leader_keymap,
  [sym__leader_keymap] = sym__leader_keymap,
  [sym_leader_key] = sym_leader_key,
  [sym__leader_key] = sym__leader_key,
  [sym_key] = sym_key,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__hotkey_repeat1] = aux_sym__hotkey_repeat1,
  [aux_sym__leader_keymap_repeat1] = aux_sym__leader_keymap_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LTleader_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_modifier_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_key_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_key_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token6] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token7] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token8] = {
    .visible = false,
    .named = false,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_set_leader] = {
    .visible = true,
    .named = true,
  },
  [sym__set_leader] = {
    .visible = false,
    .named = true,
  },
  [sym_keymap] = {
    .visible = true,
    .named = true,
  },
  [sym_hotkey] = {
    .visible = true,
    .named = true,
  },
  [sym__hotkey] = {
    .visible = false,
    .named = true,
  },
  [sym_leader_keymap] = {
    .visible = true,
    .named = true,
  },
  [sym__leader_keymap] = {
    .visible = false,
    .named = true,
  },
  [sym_leader_key] = {
    .visible = true,
    .named = true,
  },
  [sym__leader_key] = {
    .visible = false,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__hotkey_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__leader_keymap_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 7,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 25,
  [28] = 23,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(139);
      ADVANCE_MAP(
        '#', 183,
        '+', 144,
        '-', 145,
        ':', 176,
        '<', 18,
        'B', 162,
        'b', 162,
        'C', 163,
        'c', 163,
        'D', 164,
        'd', 164,
        'E', 171,
        'e', 171,
        'F', 161,
        'f', 161,
        'G', 174,
        'g', 174,
        'H', 172,
        'h', 172,
        'L', 167,
        'l', 167,
        'M', 170,
        'm', 170,
        'P', 165,
        'p', 165,
        'Q', 175,
        'q', 175,
        'R', 168,
        'r', 168,
        'S', 169,
        's', 169,
        'T', 166,
        't', 166,
        'U', 173,
        'u', 173,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          (',' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '=') ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '`') ADVANCE(157);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(160);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(178);
      if (lookahead == '#') ADVANCE(181);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(177);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(180);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(179);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '#', 183,
        ':', 176,
        'B', 162,
        'b', 162,
        'C', 163,
        'c', 163,
        'D', 164,
        'd', 164,
        'E', 171,
        'e', 171,
        'F', 161,
        'f', 161,
        'G', 174,
        'g', 174,
        'H', 172,
        'h', 172,
        'L', 167,
        'l', 167,
        'M', 170,
        'm', 170,
        'P', 165,
        'p', 165,
        'Q', 175,
        'q', 175,
        'R', 168,
        'r', 168,
        'S', 169,
        's', 169,
        'T', 166,
        't', 166,
        'U', 173,
        'u', 173,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          (',' <= lookahead && lookahead <= '/') ||
          lookahead == ';' ||
          lookahead == '=' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '`') ADVANCE(157);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(160);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(141);
      END_STATE();
    case 7:
      if (lookahead == '_') ADVANCE(43);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(95);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(97);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(102);
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(125);
      END_STATE();
    case 9:
      if (lookahead == '_') ADVANCE(115);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(69);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 17:
      ADVANCE_MAP(
        'e', 11,
        'A', 71,
        'a', 71,
        'C', 76,
        'c', 76,
        'O', 100,
        'o', 100,
        'S', 61,
        's', 61,
      );
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(140);
      END_STATE();
    case 21:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(112);
      END_STATE();
    case 22:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(129);
      END_STATE();
    case 23:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(158);
      END_STATE();
    case 24:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 25:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 26:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(107);
      END_STATE();
    case 27:
      ADVANCE_MAP(
        'A', 71,
        'a', 71,
        'C', 76,
        'c', 76,
        'O', 100,
        'o', 100,
        'S', 61,
        's', 61,
      );
      END_STATE();
    case 28:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(88);
      END_STATE();
    case 29:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(146);
      END_STATE();
    case 31:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(109);
      END_STATE();
    case 32:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(134);
      END_STATE();
    case 33:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(147);
      END_STATE();
    case 34:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(135);
      END_STATE();
    case 35:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(136);
      END_STATE();
    case 36:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(137);
      END_STATE();
    case 37:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(91);
      END_STATE();
    case 38:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 39:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(152);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(49);
      END_STATE();
    case 40:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(158);
      END_STATE();
    case 41:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 42:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(142);
      END_STATE();
    case 43:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(95);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(97);
      END_STATE();
    case 44:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(152);
      END_STATE();
    case 45:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(146);
      END_STATE();
    case 46:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(158);
      END_STATE();
    case 47:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 48:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 49:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(104);
      END_STATE();
    case 50:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(117);
      END_STATE();
    case 51:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 52:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 53:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(118);
      END_STATE();
    case 54:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(119);
      END_STATE();
    case 55:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(60);
      END_STATE();
    case 56:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(73);
      END_STATE();
    case 57:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(47);
      END_STATE();
    case 58:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(158);
      END_STATE();
    case 59:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(142);
      END_STATE();
    case 60:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(118);
      END_STATE();
    case 61:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(65);
      END_STATE();
    case 62:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 63:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 64:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 65:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 66:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(148);
      END_STATE();
    case 67:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(159);
      END_STATE();
    case 68:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(142);
      END_STATE();
    case 69:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 70:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(96);
      END_STATE();
    case 71:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(119);
      END_STATE();
    case 72:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(92);
      END_STATE();
    case 73:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 74:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(44);
      END_STATE();
    case 75:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(63);
      END_STATE();
    case 76:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(42);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(80);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(110);
      END_STATE();
    case 77:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(78);
      END_STATE();
    case 78:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(23);
      END_STATE();
    case 79:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 80:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(79);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(124);
      END_STATE();
    case 81:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(152);
      END_STATE();
    case 82:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(146);
      END_STATE();
    case 83:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(158);
      END_STATE();
    case 84:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(151);
      END_STATE();
    case 85:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(142);
      END_STATE();
    case 86:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(126);
      END_STATE();
    case 87:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 88:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 89:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 90:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(122);
      END_STATE();
    case 91:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 92:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(83);
      END_STATE();
    case 93:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 94:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(85);
      END_STATE();
    case 95:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(131);
      END_STATE();
    case 96:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 97:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(151);
      END_STATE();
    case 98:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(113);
      END_STATE();
    case 99:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(45);
      END_STATE();
    case 100:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(120);
      END_STATE();
    case 101:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(52);
      END_STATE();
    case 102:
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(125);
      END_STATE();
    case 103:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 104:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(146);
      END_STATE();
    case 105:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(142);
      END_STATE();
    case 106:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(132);
      END_STATE();
    case 107:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 108:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 109:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 110:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 111:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 112:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(58);
      END_STATE();
    case 113:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(150);
      END_STATE();
    case 114:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(158);
      END_STATE();
    case 115:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(69);
      END_STATE();
    case 116:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(69);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(64);
      END_STATE();
    case 117:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(158);
      END_STATE();
    case 118:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(153);
      END_STATE();
    case 119:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(142);
      END_STATE();
    case 120:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(143);
      END_STATE();
    case 121:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(127);
      END_STATE();
    case 122:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(46);
      END_STATE();
    case 123:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(45);
      END_STATE();
    case 124:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(111);
      END_STATE();
    case 125:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(90);
      END_STATE();
    case 126:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(114);
      END_STATE();
    case 127:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(108);
      END_STATE();
    case 128:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 129:
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(46);
      END_STATE();
    case 130:
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(81);
      END_STATE();
    case 131:
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(84);
      END_STATE();
    case 132:
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(26);
      END_STATE();
    case 133:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(101);
      END_STATE();
    case 134:
      if (lookahead == 'K' ||
          lookahead == 'k' ||
          lookahead == 0x212a) ADVANCE(116);
      END_STATE();
    case 135:
      if (lookahead == 'K' ||
          lookahead == 'k' ||
          lookahead == 0x212a) ADVANCE(158);
      END_STATE();
    case 136:
      if (lookahead == 'K' ||
          lookahead == 'k' ||
          lookahead == 0x212a) ADVANCE(149);
      END_STATE();
    case 137:
      if (lookahead == 'K' ||
          lookahead == 'k' ||
          lookahead == 0x212a) ADVANCE(50);
      END_STATE();
    case 138:
      if (eof) ADVANCE(139);
      ADVANCE_MAP(
        '#', 183,
        '+', 144,
        '-', 145,
        ':', 176,
        '<', 18,
        'l', 17,
        'A', 71,
        'a', 71,
        'C', 76,
        'c', 76,
        'H', 133,
        'h', 133,
        'M', 51,
        'm', 51,
        'O', 100,
        'o', 100,
        'S', 61,
        's', 61,
        'L', 27,
        'R', 27,
        'r', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(138);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_directive);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_LTleader_GT);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_modifier);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_modifier);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(94);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_modifier_operator);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_key_operator);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_key_token1);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_key_token1);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(99);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_key_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(123);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_key_token2);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_key_token2);
      if (lookahead == '_') ADVANCE(70);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(96);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_key_token3);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_key_token4);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_key_token4);
      if (lookahead == '_') ADVANCE(31);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(109);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_key_token5);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_key_token5);
      if (lookahead == '0') ADVANCE(154);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_key_token5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_key_token6);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_key_token7);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(aux_sym_key_token7);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(158);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(aux_sym_key_token8);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == '1') ADVANCE(156);
      if (lookahead == '2') ADVANCE(155);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(106);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(98);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(77);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(112);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(66);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(130);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(121);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(aux_sym_key_token8);
      ADVANCE_MAP(
        'E', 75,
        'e', 75,
        'I', 87,
        'i', 87,
        'L', 21,
        'l', 21,
        'P', 25,
        'p', 25,
      );
      END_STATE();
    case 170:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(86);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(39);
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(128);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(33);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(74);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(152);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(aux_sym_key_token8);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(90);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_separator);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_command);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '\n') ADVANCE(178);
      if (lookahead == '#') ADVANCE(181);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '\n') ADVANCE(179);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_command);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(177);
      if (lookahead == '\\') ADVANCE(182);
      if (lookahead != 0) ADVANCE(181);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(180);
      if (lookahead == '\\') ADVANCE(182);
      if (lookahead != 0) ADVANCE(181);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(183);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 138},
  [2] = {.lex_state = 138},
  [3] = {.lex_state = 138},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 138},
  [14] = {.lex_state = 138},
  [15] = {.lex_state = 138},
  [16] = {.lex_state = 138},
  [17] = {.lex_state = 138},
  [18] = {.lex_state = 138},
  [19] = {.lex_state = 138},
  [20] = {.lex_state = 138},
  [21] = {.lex_state = 138},
  [22] = {.lex_state = 138},
  [23] = {.lex_state = 138},
  [24] = {.lex_state = 138},
  [25] = {.lex_state = 138},
  [26] = {.lex_state = 138},
  [27] = {.lex_state = 138},
  [28] = {.lex_state = 138},
  [29] = {.lex_state = 138},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 138},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LTleader_GT] = ACTIONS(1),
    [sym_modifier_operator] = ACTIONS(1),
    [sym_key_operator] = ACTIONS(1),
    [aux_sym_key_token1] = ACTIONS(1),
    [aux_sym_key_token2] = ACTIONS(1),
    [aux_sym_key_token3] = ACTIONS(1),
    [aux_sym_key_token4] = ACTIONS(1),
    [aux_sym_key_token5] = ACTIONS(1),
    [aux_sym_key_token6] = ACTIONS(1),
    [aux_sym_key_token7] = ACTIONS(1),
    [aux_sym_key_token8] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym__definition] = STATE(2),
    [sym_set_leader] = STATE(2),
    [sym__set_leader] = STATE(16),
    [sym_keymap] = STATE(2),
    [sym_hotkey] = STATE(35),
    [sym__hotkey] = STATE(13),
    [sym_leader_keymap] = STATE(2),
    [sym__leader_keymap] = STATE(17),
    [sym_leader_key] = STATE(4),
    [sym__leader_key] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_directive] = ACTIONS(7),
    [anon_sym_LTleader_GT] = ACTIONS(9),
    [sym_modifier] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_directive,
    ACTIONS(9), 1,
      anon_sym_LTleader_GT,
    ACTIONS(11), 1,
      sym_modifier,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_leader_key,
    STATE(8), 1,
      sym__leader_key,
    STATE(13), 1,
      sym__hotkey,
    STATE(16), 1,
      sym__set_leader,
    STATE(17), 1,
      sym__leader_keymap,
    STATE(35), 1,
      sym_hotkey,
    STATE(3), 5,
      sym__definition,
      sym_set_leader,
      sym_keymap,
      sym_leader_keymap,
      aux_sym_source_file_repeat1,
  [41] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_directive,
    ACTIONS(20), 1,
      anon_sym_LTleader_GT,
    ACTIONS(23), 1,
      sym_modifier,
    STATE(4), 1,
      sym_leader_key,
    STATE(8), 1,
      sym__leader_key,
    STATE(13), 1,
      sym__hotkey,
    STATE(16), 1,
      sym__set_leader,
    STATE(17), 1,
      sym__leader_keymap,
    STATE(35), 1,
      sym_hotkey,
    STATE(3), 5,
      sym__definition,
      sym_set_leader,
      sym_keymap,
      sym_leader_keymap,
      aux_sym_source_file_repeat1,
  [82] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      sym_separator,
    ACTIONS(28), 2,
      aux_sym_key_token4,
      aux_sym_key_token8,
    STATE(5), 2,
      sym_key,
      aux_sym__leader_keymap_repeat1,
    ACTIONS(26), 6,
      aux_sym_key_token1,
      aux_sym_key_token2,
      aux_sym_key_token3,
      aux_sym_key_token5,
      aux_sym_key_token6,
      aux_sym_key_token7,
  [105] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      sym_separator,
    ACTIONS(28), 2,
      aux_sym_key_token4,
      aux_sym_key_token8,
    STATE(6), 2,
      sym_key,
      aux_sym__leader_keymap_repeat1,
    ACTIONS(26), 6,
      aux_sym_key_token1,
      aux_sym_key_token2,
      aux_sym_key_token3,
      aux_sym_key_token5,
      aux_sym_key_token6,
      aux_sym_key_token7,
  [128] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      sym_separator,
    ACTIONS(37), 2,
      aux_sym_key_token4,
      aux_sym_key_token8,
    STATE(6), 2,
      sym_key,
      aux_sym__leader_keymap_repeat1,
    ACTIONS(34), 6,
      aux_sym_key_token1,
      aux_sym_key_token2,
      aux_sym_key_token3,
      aux_sym_key_token5,
      aux_sym_key_token6,
      aux_sym_key_token7,
  [151] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 2,
      aux_sym_key_token4,
      aux_sym_key_token8,
    ACTIONS(42), 7,
      aux_sym_key_token1,
      aux_sym_key_token2,
      aux_sym_key_token3,
      aux_sym_key_token5,
      aux_sym_key_token6,
      aux_sym_key_token7,
      sym_separator,
  [168] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 2,
      aux_sym_key_token4,
      aux_sym_key_token8,
    ACTIONS(46), 7,
      aux_sym_key_token1,
      aux_sym_key_token2,
      aux_sym_key_token3,
      aux_sym_key_token5,
      aux_sym_key_token6,
      aux_sym_key_token7,
      sym_separator,
  [185] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(14), 1,
      sym_key,
    ACTIONS(28), 2,
      aux_sym_key_token4,
      aux_sym_key_token8,
    ACTIONS(26), 6,
      aux_sym_key_token1,
      aux_sym_key_token2,
      aux_sym_key_token3,
      aux_sym_key_token5,
      aux_sym_key_token6,
      aux_sym_key_token7,
  [204] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(14), 1,
      sym_key,
    ACTIONS(52), 2,
      aux_sym_key_token4,
      aux_sym_key_token8,
    ACTIONS(50), 6,
      aux_sym_key_token1,
      aux_sym_key_token2,
      aux_sym_key_token3,
      aux_sym_key_token5,
      aux_sym_key_token6,
      aux_sym_key_token7,
  [223] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(15), 1,
      sym_key,
    ACTIONS(28), 2,
      aux_sym_key_token4,
      aux_sym_key_token8,
    ACTIONS(26), 6,
      aux_sym_key_token1,
      aux_sym_key_token2,
      aux_sym_key_token3,
      aux_sym_key_token5,
      aux_sym_key_token6,
      aux_sym_key_token7,
  [242] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(15), 1,
      sym_key,
    ACTIONS(52), 2,
      aux_sym_key_token4,
      aux_sym_key_token8,
    ACTIONS(50), 6,
      aux_sym_key_token1,
      aux_sym_key_token2,
      aux_sym_key_token3,
      aux_sym_key_token5,
      aux_sym_key_token6,
      aux_sym_key_token7,
  [261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 5,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
      sym_separator,
  [272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
      sym_separator,
  [283] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 5,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
      sym_separator,
  [294] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 4,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
  [304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 4,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
  [314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 4,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
  [324] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 4,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
  [334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 4,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
  [344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 4,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
  [354] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 4,
      ts_builtin_sym_end,
      sym_directive,
      anon_sym_LTleader_GT,
      sym_modifier,
  [364] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_modifier_operator,
    ACTIONS(74), 1,
      sym_key_operator,
    STATE(25), 1,
      aux_sym__hotkey_repeat1,
  [377] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_modifier,
    STATE(13), 1,
      sym__hotkey,
    STATE(18), 1,
      sym_hotkey,
  [390] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_modifier_operator,
    ACTIONS(78), 1,
      sym_key_operator,
    STATE(26), 1,
      aux_sym__hotkey_repeat1,
  [403] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_modifier_operator,
    ACTIONS(83), 1,
      sym_key_operator,
    STATE(26), 1,
      aux_sym__hotkey_repeat1,
  [416] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_modifier_operator,
    ACTIONS(85), 1,
      sym_key_operator,
    STATE(26), 1,
      aux_sym__hotkey_repeat1,
  [429] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_modifier_operator,
    ACTIONS(87), 1,
      sym_key_operator,
    STATE(27), 1,
      aux_sym__hotkey_repeat1,
  [442] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      sym_modifier_operator,
      sym_key_operator,
  [450] = 2,
    ACTIONS(89), 1,
      sym_command,
    ACTIONS(91), 1,
      sym_comment,
  [457] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_modifier,
  [464] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
  [471] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_separator,
  [478] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_command,
  [485] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym_separator,
  [492] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_command,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 105,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 151,
  [SMALL_STATE(8)] = 168,
  [SMALL_STATE(9)] = 185,
  [SMALL_STATE(10)] = 204,
  [SMALL_STATE(11)] = 223,
  [SMALL_STATE(12)] = 242,
  [SMALL_STATE(13)] = 261,
  [SMALL_STATE(14)] = 272,
  [SMALL_STATE(15)] = 283,
  [SMALL_STATE(16)] = 294,
  [SMALL_STATE(17)] = 304,
  [SMALL_STATE(18)] = 314,
  [SMALL_STATE(19)] = 324,
  [SMALL_STATE(20)] = 334,
  [SMALL_STATE(21)] = 344,
  [SMALL_STATE(22)] = 354,
  [SMALL_STATE(23)] = 364,
  [SMALL_STATE(24)] = 377,
  [SMALL_STATE(25)] = 390,
  [SMALL_STATE(26)] = 403,
  [SMALL_STATE(27)] = 416,
  [SMALL_STATE(28)] = 429,
  [SMALL_STATE(29)] = 442,
  [SMALL_STATE(30)] = 450,
  [SMALL_STATE(31)] = 457,
  [SMALL_STATE(32)] = 464,
  [SMALL_STATE(33)] = 471,
  [SMALL_STATE(34)] = 478,
  [SMALL_STATE(35)] = 485,
  [SMALL_STATE(36)] = 492,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__leader_keymap_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__leader_keymap_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__leader_keymap_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leader_key, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leader_key, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hotkey, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hotkey, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hotkey, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_leader, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leader_keymap, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__set_leader, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keymap, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__leader_keymap, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__leader_keymap, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hotkey_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__hotkey_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [95] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_skbdrc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "skbdrc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
